const EX={PERI:'Radiografia periapical',BW:'Interproximal (bitewing)',PAN:'Radiografia panorâmica',OCL:'Radiografia oclusal',TELE:'Telerradiografia',CBCT:'Tomografia de feixe cônico',SCAN:'Escaneamento intraoral'};
const SEC={d:'Diagnóstico',p:'Planejamento',r:'Prática'};
const aliases={'Cárie proximal':'carie entre dentes','Lesão periapical (periodontite apical)':'infecção ponta raiz canal mancha raiz','Extração de sisos: quando indicar e o que avaliar':'siso dente do juizo terceiro molar','Insucesso em implantes: perda óssea, posição e nervo':'falha implante peri-implantite',"Caninos inclusos":'canino preso nao nasceu impactado ortodontia tracao',"Reabsorção cervical invasiva":'reabsorcao externa cervical mancha rosea','Lentes de contato dental: avaliação antes e depois':'facetas lente dental','DTM e bruxismo: quando a imagem ajuda':'dor mandibula articulação ranger dentes','Gestantes e crianças':'gravidez gravida criança infantil','Perda óssea horizontal e vertical':'periodontite gengiva osso furca bolsa','Fratura radicular vertical':'raiz rachada trinca dente tratado canal','Cisto dentígero':'cisto siso incluso folículo queratocisto ameloblastoma','Displasia cemento-óssea':'displasia florida lesão fibro-óssea falsa lesão periapical','Calcificações na panorâmica: carótida, sialólito, tonsilólito':'ateroma carótida pedra glândula salivar amígdala achado incidental','Sinusite de origem odontogênica':'seio maxilar sinusite dente infecção','Fraturas dentoalveolares e luxações':'trauma pancada queda dente quebrado avulsão','Dose de radiação: exames comparados':'radiação dose segurança raio x microsievert'};
const featured={'lesao-periapical.html':['Lesão periapical','Quando a radiografia não mostra tudo.'],'carie-proximal.html':['Cárie proximal','O que a interproximal mostra e o que ela esconde.'],'extracao-sisos.html':['Extração de sisos','Quando indicar e o que avaliar na imagem.'],'insucesso-implantes.html':['Insucesso em implantes','Perda óssea, posição e acompanhamento.'],'caninos-inclusos.html':['Caninos inclusos','Quando a panorâmica basta e quando pedir CBCT.'],'reabsorcao-cervical-invasiva.html':['Reabsorção cervical invasiva','Confirmar a suspeita e avaliar a extensão.'],'lentes-contato-dental.html':['Lentes de contato dental','O que avaliar antes e depois.'],'perda-ossea-periodontal.html':['Perda óssea periodontal','Como ler a crista óssea e classificar a periodontite.'],'fratura-radicular-vertical.html':['Fratura radicular vertical','Sinais indiretos e os limites da CBCT.'],'cisto-dentigero.html':['Cisto dentígero','Quando o folículo do dente incluso vira lesão.'],'displasia-cemento-ossea.html':['Displasia cemento-óssea','A falsa lesão periapical em dente vital.'],'calcificacoes-panoramica.html':['Calcificações na panorâmica','Carótida, glândula salivar ou amígdala?'],'sinusite-odontogenica.html':['Sinusite odontogênica','Quando o dente é a causa da sinusite.'],'trauma-dentoalveolar.html':['Trauma dentoalveolar','Que radiografias pedir e como acompanhar.'],'dose-radiacao.html':['Dose de radiação','Exames comparados, em números.']};
const $=s=>document.querySelector(s),norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search);let state={q:params.get('q')||'',s:params.get('s')||'',x:params.get('x')||'',p:params.get('p')==='1'};
if(!SEC[state.s])state.s='';if(!EX[state.x])state.x='';
$('#sectionFilters').innerHTML=[['','Todos os temas'],...Object.entries(SEC)].filter(([k])=>!k||CATALOG.some(d=>d.s===k)).map(([k,title])=>`<button class="section-filter" data-section="${k}" aria-pressed="false">${title}<span>${CATALOG.filter(d=>!k||d.s===k).length}</span></button>`).join('');
$('#exam').insertAdjacentHTML('beforeend',Object.keys(EX).filter(k=>CATALOG.some(d=>[...d.e,...d.c].includes(k))).map(k=>`<option value="${k}">${k} · ${EX[k]}</option>`).join(''));$('#glossaryList').innerHTML=Object.entries(EX).map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('');
function chip(k){return `<span class="chip" title="${EX[k]}">${k}</span>`;}
function path(d){if(!d.e.length&&!d.c.length)return '<span>Fontes oficiais · sem exame associado</span>';return `${d.e.length?'<span class="path-label">Partida</span>'+d.e.map(chip).join(''):''}${d.c.length?'<span class="path-label">Complementar se indicado</span>'+d.c.map(chip).join(''):''}`;}
function matches(d){return(!state.s||d.s===state.s)&&(!state.x||[...d.e,...d.c].includes(state.x))&&(!state.p||d.p)&&(!state.q||norm([d.t,d.a,SEC[d.s],aliases[d.t]||'',...d.e.map(x=>EX[x]),...d.c.map(x=>EX[x])].join(' ')).includes(norm(state.q.trim())));}
function sync(){const p=new URLSearchParams();for(const k of ['q','s','x'])if(state[k])p.set(k,state[k]);if(state.p)p.set('p','1');history.replaceState(null,'',location.pathname+(p.size?'?'+p:'')+location.hash);}
function render(){const list=CATALOG.filter(matches);const available=list.filter(d=>d.u);$('#count').textContent=`${list.length} de ${CATALOG.length} temas · ${available.length} ${available.length===1?'ficha disponível':'fichas disponíveis'}`;$('#clear').hidden=!Object.values(state).some(Boolean);$('#q').value=state.q;$('#exam').value=state.x;$('#patientFilter').checked=state.p;document.querySelectorAll('[data-section]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.section===state.s)));if(!list.length){$('#out').innerHTML='<div class="empty"><h2>Nenhum tema encontrado</h2><p>Tente outra palavra ou amplie os filtros.</p><button id="emptyClear">Ver todos os temas</button></div>';$('#emptyClear').onclick=clear;sync();return;}
let output=available.length?`<div class="available-title"><h2>Fichas da biblioteca</h2></div><div class="available-grid">${available.map(d=>{const info=featured[d.u]||[d.t,d.a];return `<a class="available-card" href="${d.u}"><p class="eyebrow">${SEC[d.s]} · ${esc(d.a)}</p><h3>${esc(info[0])}</h3><p>${esc(info[1])}</p><div class="card-meta"><span>${d.e.map(chip).join(' ')}</span><span>Texto técnico + paciente</span></div></a>`;}).join('')}</div>`:'';
output+=Object.entries(SEC).map(([s,title])=>{const items=list.filter(d=>d.s===s);if(!items.length)return '';return `<section class="catalog-section"><div class="section-heading"><h2>${title}</h2><span>${items.length} ${items.length===1?'tema':'temas'}</span></div><div class="areas">${[...new Set(items.map(d=>d.a))].map(a=>`<div class="area"><h3>${esc(a)}</h3><ul>${items.filter(d=>d.a===a).map(d=>`<li class="item"><div class="item-top">${d.u?`<a class="item-title" href="${d.u}">${esc(d.t)}</a>`:`<span class="item-title">${esc(d.t)}</span>`}<span class="item-status ${d.u?'ready':''}">Consultar</span></div><div class="exam-path">${path(d)}</div>${d.p?'<div class="patient-mark">Também para pacientes</div>':''}</li>`).join('')}</ul></div>`).join('')}</div></section>`;}).join('');$('#out').innerHTML=output;sync();}
function clear(){state={q:'',s:'',x:'',p:false};render();}$('#clear').onclick=clear;$('#q').oninput=e=>{state.q=e.target.value;render();};$('#exam').onchange=e=>{state.x=e.target.value;render();};$('#patientFilter').onchange=e=>{state.p=e.target.checked;render();};$('#sectionFilters').onclick=e=>{const b=e.target.closest('[data-section]');if(b){state.s=b.dataset.section;render();}};
const glossary=$('#glossary');$('#glossaryOpen').onclick=()=>glossary.showModal();glossary.querySelector('.dialog-close').onclick=()=>glossary.close();document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!glossary.open){e.preventDefault();$('#q').focus();}});
$('#out').addEventListener('click',e=>{if(e.target.closest('a'))try{sessionStorage.setItem('cor-catalog-return',location.href);}catch{}});
const legacyRoutes={'1':'lesao-periapical.html','2':'carie-proximal.html','11':'index.html?q=fratura%20radicular#catalogo','33':'insucesso-implantes.html','35':'extracao-sisos.html'};const legacy=location.hash.match(/^#tema\/(\d+)$/);if(legacy){const target=legacyRoutes[legacy[1]];if(target)location.replace(target);else history.replaceState(null,'',location.pathname+'#catalogo');}render();
